### ISSUE TITLE
Ta moderninho

### ISSUE THREAD

**Issue by gsoldateli** [trialforce/blend#1]
Abrindo a Issue pra falar que esse menino ta muito moderninnho.

**Comment by gsoldateli** [comment]
> Gangue dos moderninhos.
@moiseh

**Comment by moiseh** [comment]
Este menino não veio para vida a passeio

**Comment by trialforce** [comment]
Fala Galera, valeu pelos comentários.

Daqui uns dias vai ter repositório de exemplos e composer.
