### ISSUE TITLE
\Page\Page - Ajustar método getHead()

### ISSUE THREAD

**Issue by wehrmeier** [trialforce/blend#10]
Se faz necessário ajustar o método getHead() para que o título da página seja distribuído a outro método. O método deverá ser chamado de getFormTitle() e nele retornado um elemento span com as definições para o campo. Abaixo segue um exemplo:

```
    public function getFormTitle()
    {
        return new \View\Span('extraTitle', array($this->getIcon(), $this->getTitle()));
    }
```

Dessa forma o usuário poderá sobrescrever o método getFormTitle() e assim definir o título que melhor se encaixa em sua necessidade.

**Comment by trialforce** [comment]
Você quer fazer um título personalizado para o seu form?
Isto?
