### ISSUE TITLE
\Component\Combo - Ajustar método getId()

### ISSUE THREAD

**Issue by wehrmeier** [trialforce/blend#12]
Se faz necessário ajustar o método getId() do componente Combo para que respeite o método getFormName() quando utilizado. Obs: não é nem de perto a melhor solução pra o problema mas, funcionou bem para os casos onde há diversos modais sendo abertos.

Exemplo:
```
    public function getId()
    {

        $formName = '';
        $dom = \View\View::getDom();
        if (method_exists($dom, 'getFormName') && $dom->getFormName())
        {
            $formName = $dom->getFormName();
        }

        return $this->id . $formName;
    }
```

**Comment by trialforce** [comment]
Acredito que este precisamos avaliar em conjunto.
