### ISSUE TITLE
\View\Layout - Ajustar método getElementById(...)

### ISSUE THREAD

**Issue by wehrmeier** [trialforce/blend#13]
Se faz necessário ajustar o método getElementById da classe \View\Layout para os casos onde o formName é utilizado. Hoje, o método apenas está considerando o id informado pelo usuário. A partir da utilização do formName o método deve então considerar possíveis id compostos de "nome da coluna" + formName caso o id contendo "nome da coluna" não exista. Para resolver meu problema, sobrescrevi o método em uma classe filha onde utilizo o método natural getElementById() para capturar os dois elementos se necessário.

Exemplo:

```
    public function getElementById($elementId, $class = NULL)
    {
        $element = parent::getElementById($elementId, $class);
        if ($element && substr($element->getId(), 0, strlen(\View\View::REPLACE_SHARP)) == \View\View::REPLACE_SHARP)
        {
            $elementFormName = parent::getElementById($elementId . self::getFormName(), $class);
            if ($elementFormName && substr($elementFormName->getId(), 0, strlen(\View\View::REPLACE_SHARP)) != \View\View::REPLACE_SHARP)
            {
                $element = $elementFormName;
            }
        }

        return $element;
    }
```

**Comment by trialforce** [comment]
Achei meio estranho, você pega o element normal, depois tenta pegar element com formName.

Não faria mais sentido verificar se existe o formName pegar pelo formName e caso não encontrar pegar pelo id normal.

Da forma como você fez ele só vai procurar por "formName_id" caso "id" exista. Acredito que não seja o ideial.

Pseudo código.

```
if ( self::getFormName() )
{
     $element = parent::getElementById($elementId . self::getFormName(), $class);
}
else
{
     $element = parent::getElementById($elementId, $class);
}
```

De qualquer forma o getElementById tem bem mais código, como ficou essa parte?

Eu não sei se você reparou mais o \View\Layout tem um sistema que controla a lista de elementos criados.

````
addToElementList($element)
````

Toda view que tem seu id definido é adicionada a lista de elementos.  (Arquivo \View\View na linha 287). 
Isso é necessário para otimização, pois procurar todos os elementos direto no dom é bem custoso em processamento.

Acredito que para resolver o problema seria só fazer o addElementList levando em conta o formName. e no getElementById também fazer a mesma coisa.

Exemplo (não testado):

```
    /**
     * Adiciona um elemento a lista de elementos.
     * Dessa forma ele pode ser localizado pelo getElementById a qualquer momento
     *
     * @param DomElement $element
     */
    public function addToElementList(\DomElement $element)
    {
        $id = $element->getAttribute('id');
        $this->elementList[self::getFormName().'_'.$id] = $element;
    }
```

No getElementByid

```
public function getElementById($elementId, $class = NULL)
    {
        //se não passou o id não rola né?
        if (!$elementId)
        {
            return NULL;
        }

        //compatibilidade com jquery
        $elementId = str_replace('#', '', $elementId);

        //tenta o atalho pelo elemento com formname registrado
        if (isset($this->elementList[self::getFormName().'_'.$elementId]))
        {
            return $this->elementList[self::getFormName().'_'.$elementId];
        }

        //tenta o atalho pelo elemento registrado
        if (isset($this->elementList[$elementId]))
        {
            return $this->elementList[$elementId];
        }

```

**Comment by trialforce** [comment]
Acredito que não seja necessário o '_' na concatenizacao formName e campo.

**Comment by trialforce** [comment]
Avaliei um pouco mais a fundo o issue e acho que fazer isso 100% automático não é uma boa.

O ticket #7 foi resolvido e foram aplicados o formName nas tabs e nos campos. Se deixarmos o formName fixo no getElementById nunca poderemos pegar o id padrão do form principal ou de outro futuro formName.

Quando quiser pegar um que tenha ou não o formName pode fazer da seguinte forma:

```
$this->byId($this->getFormName() . 'id')->hide();
```

Vai funcionar em casos com e sem formName.
