### ISSUE TITLE
\Component\Grid\EditPopupGrid - Ajustar paginação

### ISSUE THREAD

**Issue by wehrmeier** [trialforce/blend#6]
Se faz necessário ajustar a paginação das grid internas para que não submeta o formulário ao ser acionada. Hoje, ao "navegar" entre uma página e outra o formulário geral está sendo enviado e a aba que contém a grid perde sua seleção.

**Comment by trialforce** [comment]
Esse eu já tinha feito no Blend. Só não tinha comentado porque achei que impactaria no netControl. 
Em seguida explico onde tem que mudar e você testa e retorna.
