### ISSUE TITLE
\Fieldlayout\Vector - Ajustar id das abas

### ISSUE THREAD

**Issue by wehrmeier** [trialforce/blend#7]
Se faz necessário ajustar o id das abas para que também passe a respeitar o valor definido pelo método getFormName(). Dessa forma, não haverá problemas quanto a abertura de outros cadastros em forma de popup. Hoje, se tiver uma aba no cadastro pai com id "tab-principal" e outra aba no cadastro filho aberto com popup com id "tab-principal" o javascript vai apenas mudar a seleção da aba do pai, ignorando a aba que está sendo requerida.

Para ajustar tal problema pode substituir o método onCreate pelo script abaixo:
```
public function onCreate()
    {
        if (is_array($this->array))
        {
            $array = array_values($this->array);
            $innerArray = array_values($array[0]);
            $makeTab = is_array($innerArray[0]);
        }
        else
        {
            $makeTab = false;
        }

        if ($makeTab)
        {
            $tabs = $this->array;
            $tab = new \View\Ext\Tab('fieldLayoutTab');

            $formName = '';
            $dom = \View\View::getDom();
            if (method_exists($dom, 'getFormName') && $dom->getFormName())
            {
                $formName = $dom->getFormName();
            }

            foreach ($tabs as $label => $campos)
            {
                $id = \Type\Text::get($label)->toFile();
                $this->array = $campos;
                $tab->add('tab-' . $formName . '-' . $id, $label, $this->createFieldLayout());
            }

            return $tab;
        }
        else
        {
            return $this->createFieldLayout();
        }
    }
```

**Comment by trialforce** [comment]
Nunca tive problema com isso pois sempre usava nomes de abas diferentes entre pai e filho.

Mas é válido sim. Na verdade isto está relacionado com a questão dos ids.

**Comment by trialforce** [comment]
Estou pensando numa solução mais abrangente onde TODOS ids criados em uma página com formName ganham ele como prefixo e após isso o byId pegas eles por prefixo também.

Eu te confesso que não gosto muito desse tipo de regra, pois fica fácil para programar via PHP, mas o programador que vai acessar o html vai javascript tem que entender que o id do html não é o mesmo. 

Pois o jquery não vai entender isso, mas okay.

Ferra a ideia de manter 1x1 com o jquery, mas facilita a programação.

**Comment by trialforce** [comment]
Além disso, neste caso você poderia manualmente criar com o id com "formName_tabname" e mudar a label da tab para o valor que você quiser via programação.

**Comment by trialforce** [comment]
Resolvido, todos elementos gerados pelo vector layout levam em conta o formName, tanto as tabs quanto os campos em si, isto deve resolver a maioria dos problemas com separação de campos do form pai e filho.

Os ids ficam assim (onde rmpilotoarte é o formName).

```
<input name="rmpilotoarte[id]" id="rmpilotoarteid" type="number" value="520" keyboard="numeric" data-m-dec="0" data-a-sep="" data-a-dec="." data-v-max="99999999999999" data-v-min="-99999999999" class="integer span6 pkField" title="Código" placeholder="Código" readonly="">
```

Isso foi feito sem traço ou qualquer separado para o byId('') poder funcionar da seguinte forma:

```
$this->byId(' $this->getFormName() . 'id')->hide();
```

Dessa forma é possível passar o formName sem medo, pois quando forma vazio tem impacto zero.
O que parece resolver o seu issue 13.

Closes #13.
