### ISSUE TITLE
\View\Ext\Select

### ISSUE THREAD

**Issue by wehrmeier** [trialforce/blend#8]
Se faz necessário a criação de um novo elemento select que permita ao usuário definir uma classe a uma determinada coluna, assim como ocorre nos combos(autocomplete). É necessário que assim como ocorre no autocomplete, seja possível definir as colunas que serão apresentadas no select e também realizar filtros por parâmetros fixos e via request. Para isso acredito que a melhor maneira seja implementar o método getDataSource(...) em seu escopo.

**Comment by trialforce** [comment]
Já foi adicionado.
