### ISSUE TITLE
\Page\Page - Ajustar método getHead()

### ISSUE THREAD

**Issue by wehrmeier** [trialforce/blend#9]
Se faz necessário ajustar o método getHead() da classe \Page\Page para que passe a respeitar o valor informado no método estático getFormName(). Dessa forma, o elemento H1 da página terá um id único no sistema, impedindo que operações como abertura de cadastros via modal alterem o valor do mesmo.

**Comment by trialforce** [comment]
Entendi.

Pensou na possibilidade de fazer os Pull Requests conforme te falei?
